image: node:6.9.4

pipelines:
  default:
    - step:
        name: noop
        script:
          - echo "Click RUN on the next step to deploy it to the S3 bucket"
    - step:
        name: Deploy to S3
        trigger: manual
        caches:
          - node
        script:
          - npm install -g gulp@3.9.0
          - npm install -g bower@1.6.5

          # Create aws-credential.js
          - touch aws-credential.js
          - >
            echo -e
            "const credential = {};\n
            credential.accessKeyId = \"$AWS_ACCESS_KEY_ID\";\n
            credential.secretAccessKey = \"$AWS_SECRET_ACCESS_KEY\";\n
            credential.region = 'us-west-1';\n
            module.exports = credential;" > aws-credential.js
          - cat aws-credential.js

          # Create aws-s3-bucket-config.js
          - bucketname=zipcode.huubhr.com
          - touch aws-s3-bucket-config.js
          - >
            echo -e
            "const path = {};\n
            path.params = {\"Bucket\": \"$bucketname\"};
            module.exports = path;" > aws-s3-bucket-config.js
          - cat aws-s3-bucket-config.js

          - npm install
          - gulp clean
          - gulp zipcode_build
